server.port: 5558
  
app.addition: http://localhost:5557/addition
app.subtraction: http://localhost:5558/subtraction
app.multiplication: http://localhost:5559/multiplication
app.division: http://localhost:5560/division


trackia.dispatcher.class: trackiaServerDispatcher
trackia.dispatcher.url: https://trackiaapp.com/journal
trackia.dispatcher.auth: https://trackiaapp.com/auth/signin

trackia.dispatcher.account: <Account ID>
trackia.dispatcher.apiKey: <Artefact ApiKey>
